language: node_js
node_js:
- "lts/*"
cache:
  yarn: true
  directories:
  - node_modules
before_install:
  - export PATH=$PATH:`yarn global bin`
  - yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
- yarn build
